# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leeds Raspberry Jam
email: hello@leedsraspjam.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Main website for the Leeds Raspberry Jam events.


baseurl: "/lrj-www" # the subpath of your site, e.g. /blog
url: "https://www.leedsraspjam.co.uk" # the base hostname & protocol for your site

#sidebar
default-image: default.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

#social
facebook: http://facebook.com/leedsraspjam
twitter: http://twitter.com/@leedsraspjam
github: http://github.com/leedsraspjam
email: hello@leedsraspjam.co.uk

#facebook like box
fb-like-box: yes
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/leedsraspjam/
fb-page-title: leedsraspjam

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-redirect-from]
